/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Diagnosis } from "./Diagnosis";
import { DiagnosisCountArgs } from "./DiagnosisCountArgs";
import { DiagnosisFindManyArgs } from "./DiagnosisFindManyArgs";
import { DiagnosisFindUniqueArgs } from "./DiagnosisFindUniqueArgs";
import { CreateDiagnosisArgs } from "./CreateDiagnosisArgs";
import { UpdateDiagnosisArgs } from "./UpdateDiagnosisArgs";
import { DeleteDiagnosisArgs } from "./DeleteDiagnosisArgs";
import { PrescriptionFindManyArgs } from "../../prescription/base/PrescriptionFindManyArgs";
import { Prescription } from "../../prescription/base/Prescription";
import { Doctor } from "../../doctor/base/Doctor";
import { Patient } from "../../patient/base/Patient";
import { DiagnosisService } from "../diagnosis.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Diagnosis)
export class DiagnosisResolverBase {
  constructor(
    protected readonly service: DiagnosisService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "read",
    possession: "any",
  })
  async _diagnosesMeta(
    @graphql.Args() args: DiagnosisCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Diagnosis])
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "read",
    possession: "any",
  })
  async diagnoses(
    @graphql.Args() args: DiagnosisFindManyArgs
  ): Promise<Diagnosis[]> {
    return this.service.diagnoses(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Diagnosis, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "read",
    possession: "own",
  })
  async diagnosis(
    @graphql.Args() args: DiagnosisFindUniqueArgs
  ): Promise<Diagnosis | null> {
    const result = await this.service.diagnosis(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Diagnosis)
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "create",
    possession: "any",
  })
  async createDiagnosis(
    @graphql.Args() args: CreateDiagnosisArgs
  ): Promise<Diagnosis> {
    return await this.service.createDiagnosis({
      ...args,
      data: {
        ...args.data,

        doctor: args.data.doctor
          ? {
              connect: args.data.doctor,
            }
          : undefined,

        patient: args.data.patient
          ? {
              connect: args.data.patient,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Diagnosis)
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "update",
    possession: "any",
  })
  async updateDiagnosis(
    @graphql.Args() args: UpdateDiagnosisArgs
  ): Promise<Diagnosis | null> {
    try {
      return await this.service.updateDiagnosis({
        ...args,
        data: {
          ...args.data,

          doctor: args.data.doctor
            ? {
                connect: args.data.doctor,
              }
            : undefined,

          patient: args.data.patient
            ? {
                connect: args.data.patient,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Diagnosis)
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "delete",
    possession: "any",
  })
  async deleteDiagnosis(
    @graphql.Args() args: DeleteDiagnosisArgs
  ): Promise<Diagnosis | null> {
    try {
      return await this.service.deleteDiagnosis(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Prescription], { name: "prescriptions" })
  @nestAccessControl.UseRoles({
    resource: "Prescription",
    action: "read",
    possession: "any",
  })
  async findPrescriptions(
    @graphql.Parent() parent: Diagnosis,
    @graphql.Args() args: PrescriptionFindManyArgs
  ): Promise<Prescription[]> {
    const results = await this.service.findPrescriptions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Doctor, {
    nullable: true,
    name: "doctor",
  })
  @nestAccessControl.UseRoles({
    resource: "Doctor",
    action: "read",
    possession: "any",
  })
  async getDoctor(@graphql.Parent() parent: Diagnosis): Promise<Doctor | null> {
    const result = await this.service.getDoctor(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Patient, {
    nullable: true,
    name: "patient",
  })
  @nestAccessControl.UseRoles({
    resource: "Patient",
    action: "read",
    possession: "any",
  })
  async getPatient(
    @graphql.Parent() parent: Diagnosis
  ): Promise<Patient | null> {
    const result = await this.service.getPatient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
