/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DiagnosisService } from "../diagnosis.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DiagnosisCreateInput } from "./DiagnosisCreateInput";
import { Diagnosis } from "./Diagnosis";
import { DiagnosisFindManyArgs } from "./DiagnosisFindManyArgs";
import { DiagnosisWhereUniqueInput } from "./DiagnosisWhereUniqueInput";
import { DiagnosisUpdateInput } from "./DiagnosisUpdateInput";
import { PrescriptionFindManyArgs } from "../../prescription/base/PrescriptionFindManyArgs";
import { Prescription } from "../../prescription/base/Prescription";
import { PrescriptionWhereUniqueInput } from "../../prescription/base/PrescriptionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DiagnosisControllerBase {
  constructor(
    protected readonly service: DiagnosisService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Diagnosis })
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDiagnosis(
    @common.Body() data: DiagnosisCreateInput
  ): Promise<Diagnosis> {
    return await this.service.createDiagnosis({
      data: {
        ...data,

        doctor: data.doctor
          ? {
              connect: data.doctor,
            }
          : undefined,

        patient: data.patient
          ? {
              connect: data.patient,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        date: true,
        description: true,

        doctor: {
          select: {
            id: true,
          },
        },

        id: true,

        patient: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Diagnosis] })
  @ApiNestedQuery(DiagnosisFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async diagnoses(@common.Req() request: Request): Promise<Diagnosis[]> {
    const args = plainToClass(DiagnosisFindManyArgs, request.query);
    return this.service.diagnoses({
      ...args,
      select: {
        createdAt: true,
        date: true,
        description: true,

        doctor: {
          select: {
            id: true,
          },
        },

        id: true,

        patient: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Diagnosis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async diagnosis(
    @common.Param() params: DiagnosisWhereUniqueInput
  ): Promise<Diagnosis | null> {
    const result = await this.service.diagnosis({
      where: params,
      select: {
        createdAt: true,
        date: true,
        description: true,

        doctor: {
          select: {
            id: true,
          },
        },

        id: true,

        patient: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Diagnosis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDiagnosis(
    @common.Param() params: DiagnosisWhereUniqueInput,
    @common.Body() data: DiagnosisUpdateInput
  ): Promise<Diagnosis | null> {
    try {
      return await this.service.updateDiagnosis({
        where: params,
        data: {
          ...data,

          doctor: data.doctor
            ? {
                connect: data.doctor,
              }
            : undefined,

          patient: data.patient
            ? {
                connect: data.patient,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          date: true,
          description: true,

          doctor: {
            select: {
              id: true,
            },
          },

          id: true,

          patient: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Diagnosis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDiagnosis(
    @common.Param() params: DiagnosisWhereUniqueInput
  ): Promise<Diagnosis | null> {
    try {
      return await this.service.deleteDiagnosis({
        where: params,
        select: {
          createdAt: true,
          date: true,
          description: true,

          doctor: {
            select: {
              id: true,
            },
          },

          id: true,

          patient: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/prescriptions")
  @ApiNestedQuery(PrescriptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Prescription",
    action: "read",
    possession: "any",
  })
  async findPrescriptions(
    @common.Req() request: Request,
    @common.Param() params: DiagnosisWhereUniqueInput
  ): Promise<Prescription[]> {
    const query = plainToClass(PrescriptionFindManyArgs, request.query);
    const results = await this.service.findPrescriptions(params.id, {
      ...query,
      select: {
        createdAt: true,

        diagnosis: {
          select: {
            id: true,
          },
        },

        dosage: true,
        frequency: true,
        id: true,

        medication: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/prescriptions")
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "update",
    possession: "any",
  })
  async connectPrescriptions(
    @common.Param() params: DiagnosisWhereUniqueInput,
    @common.Body() body: PrescriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prescriptions: {
        connect: body,
      },
    };
    await this.service.updateDiagnosis({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/prescriptions")
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "update",
    possession: "any",
  })
  async updatePrescriptions(
    @common.Param() params: DiagnosisWhereUniqueInput,
    @common.Body() body: PrescriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prescriptions: {
        set: body,
      },
    };
    await this.service.updateDiagnosis({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/prescriptions")
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "update",
    possession: "any",
  })
  async disconnectPrescriptions(
    @common.Param() params: DiagnosisWhereUniqueInput,
    @common.Body() body: PrescriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prescriptions: {
        disconnect: body,
      },
    };
    await this.service.updateDiagnosis({
      where: params,
      data,
      select: { id: true },
    });
  }
}
