/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Medication } from "./Medication";
import { MedicationCountArgs } from "./MedicationCountArgs";
import { MedicationFindManyArgs } from "./MedicationFindManyArgs";
import { MedicationFindUniqueArgs } from "./MedicationFindUniqueArgs";
import { CreateMedicationArgs } from "./CreateMedicationArgs";
import { UpdateMedicationArgs } from "./UpdateMedicationArgs";
import { DeleteMedicationArgs } from "./DeleteMedicationArgs";
import { InventoryFindManyArgs } from "../../inventory/base/InventoryFindManyArgs";
import { Inventory } from "../../inventory/base/Inventory";
import { PrescriptionFindManyArgs } from "../../prescription/base/PrescriptionFindManyArgs";
import { Prescription } from "../../prescription/base/Prescription";
import { SaleFindManyArgs } from "../../sale/base/SaleFindManyArgs";
import { Sale } from "../../sale/base/Sale";
import { MedicationService } from "../medication.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Medication)
export class MedicationResolverBase {
  constructor(
    protected readonly service: MedicationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Medication",
    action: "read",
    possession: "any",
  })
  async _medicationsMeta(
    @graphql.Args() args: MedicationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Medication])
  @nestAccessControl.UseRoles({
    resource: "Medication",
    action: "read",
    possession: "any",
  })
  async medications(
    @graphql.Args() args: MedicationFindManyArgs
  ): Promise<Medication[]> {
    return this.service.medications(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Medication, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Medication",
    action: "read",
    possession: "own",
  })
  async medication(
    @graphql.Args() args: MedicationFindUniqueArgs
  ): Promise<Medication | null> {
    const result = await this.service.medication(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Medication)
  @nestAccessControl.UseRoles({
    resource: "Medication",
    action: "create",
    possession: "any",
  })
  async createMedication(
    @graphql.Args() args: CreateMedicationArgs
  ): Promise<Medication> {
    return await this.service.createMedication({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Medication)
  @nestAccessControl.UseRoles({
    resource: "Medication",
    action: "update",
    possession: "any",
  })
  async updateMedication(
    @graphql.Args() args: UpdateMedicationArgs
  ): Promise<Medication | null> {
    try {
      return await this.service.updateMedication({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Medication)
  @nestAccessControl.UseRoles({
    resource: "Medication",
    action: "delete",
    possession: "any",
  })
  async deleteMedication(
    @graphql.Args() args: DeleteMedicationArgs
  ): Promise<Medication | null> {
    try {
      return await this.service.deleteMedication(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Inventory], { name: "inventories" })
  @nestAccessControl.UseRoles({
    resource: "Inventory",
    action: "read",
    possession: "any",
  })
  async findInventories(
    @graphql.Parent() parent: Medication,
    @graphql.Args() args: InventoryFindManyArgs
  ): Promise<Inventory[]> {
    const results = await this.service.findInventories(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Prescription], { name: "prescriptions" })
  @nestAccessControl.UseRoles({
    resource: "Prescription",
    action: "read",
    possession: "any",
  })
  async findPrescriptions(
    @graphql.Parent() parent: Medication,
    @graphql.Args() args: PrescriptionFindManyArgs
  ): Promise<Prescription[]> {
    const results = await this.service.findPrescriptions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Sale], { name: "sales" })
  @nestAccessControl.UseRoles({
    resource: "Sale",
    action: "read",
    possession: "any",
  })
  async findSales(
    @graphql.Parent() parent: Medication,
    @graphql.Args() args: SaleFindManyArgs
  ): Promise<Sale[]> {
    const results = await this.service.findSales(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
