/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsNumber,
  Min,
  Max,
  IsInt,
} from "class-validator";
import { InventoryUpdateManyWithoutMedicationsInput } from "./InventoryUpdateManyWithoutMedicationsInput";
import { Type } from "class-transformer";
import { PrescriptionUpdateManyWithoutMedicationsInput } from "./PrescriptionUpdateManyWithoutMedicationsInput";
import { SaleUpdateManyWithoutMedicationsInput } from "./SaleUpdateManyWithoutMedicationsInput";

@InputType()
class MedicationUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => InventoryUpdateManyWithoutMedicationsInput,
  })
  @ValidateNested()
  @Type(() => InventoryUpdateManyWithoutMedicationsInput)
  @IsOptional()
  @Field(() => InventoryUpdateManyWithoutMedicationsInput, {
    nullable: true,
  })
  inventories?: InventoryUpdateManyWithoutMedicationsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PrescriptionUpdateManyWithoutMedicationsInput,
  })
  @ValidateNested()
  @Type(() => PrescriptionUpdateManyWithoutMedicationsInput)
  @IsOptional()
  @Field(() => PrescriptionUpdateManyWithoutMedicationsInput, {
    nullable: true,
  })
  prescriptions?: PrescriptionUpdateManyWithoutMedicationsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  quantityInStock?: number | null;

  @ApiProperty({
    required: false,
    type: () => SaleUpdateManyWithoutMedicationsInput,
  })
  @ValidateNested()
  @Type(() => SaleUpdateManyWithoutMedicationsInput)
  @IsOptional()
  @Field(() => SaleUpdateManyWithoutMedicationsInput, {
    nullable: true,
  })
  sales?: SaleUpdateManyWithoutMedicationsInput;
}

export { MedicationUpdateInput as MedicationUpdateInput };
