/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Medication as PrismaMedication,
  Inventory as PrismaInventory,
  Prescription as PrismaPrescription,
  Sale as PrismaSale,
} from "@prisma/client";

export class MedicationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.MedicationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.medication.count(args);
  }

  async medications(
    args: Prisma.MedicationFindManyArgs
  ): Promise<PrismaMedication[]> {
    return this.prisma.medication.findMany(args);
  }
  async medication(
    args: Prisma.MedicationFindUniqueArgs
  ): Promise<PrismaMedication | null> {
    return this.prisma.medication.findUnique(args);
  }
  async createMedication(
    args: Prisma.MedicationCreateArgs
  ): Promise<PrismaMedication> {
    return this.prisma.medication.create(args);
  }
  async updateMedication(
    args: Prisma.MedicationUpdateArgs
  ): Promise<PrismaMedication> {
    return this.prisma.medication.update(args);
  }
  async deleteMedication(
    args: Prisma.MedicationDeleteArgs
  ): Promise<PrismaMedication> {
    return this.prisma.medication.delete(args);
  }

  async findInventories(
    parentId: string,
    args: Prisma.InventoryFindManyArgs
  ): Promise<PrismaInventory[]> {
    return this.prisma.medication
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .inventories(args);
  }

  async findPrescriptions(
    parentId: string,
    args: Prisma.PrescriptionFindManyArgs
  ): Promise<PrismaPrescription[]> {
    return this.prisma.medication
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .prescriptions(args);
  }

  async findSales(
    parentId: string,
    args: Prisma.SaleFindManyArgs
  ): Promise<PrismaSale[]> {
    return this.prisma.medication
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .sales(args);
  }
}
