/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DoctorService } from "../doctor.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DoctorCreateInput } from "./DoctorCreateInput";
import { Doctor } from "./Doctor";
import { DoctorFindManyArgs } from "./DoctorFindManyArgs";
import { DoctorWhereUniqueInput } from "./DoctorWhereUniqueInput";
import { DoctorUpdateInput } from "./DoctorUpdateInput";
import { DiagnosisFindManyArgs } from "../../diagnosis/base/DiagnosisFindManyArgs";
import { Diagnosis } from "../../diagnosis/base/Diagnosis";
import { DiagnosisWhereUniqueInput } from "../../diagnosis/base/DiagnosisWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DoctorControllerBase {
  constructor(
    protected readonly service: DoctorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Doctor })
  @nestAccessControl.UseRoles({
    resource: "Doctor",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDoctor(@common.Body() data: DoctorCreateInput): Promise<Doctor> {
    return await this.service.createDoctor({
      data: data,
      select: {
        address: true,
        contactNumber: true,
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        specialization: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Doctor] })
  @ApiNestedQuery(DoctorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Doctor",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async doctors(@common.Req() request: Request): Promise<Doctor[]> {
    const args = plainToClass(DoctorFindManyArgs, request.query);
    return this.service.doctors({
      ...args,
      select: {
        address: true,
        contactNumber: true,
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        specialization: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Doctor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Doctor",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async doctor(
    @common.Param() params: DoctorWhereUniqueInput
  ): Promise<Doctor | null> {
    const result = await this.service.doctor({
      where: params,
      select: {
        address: true,
        contactNumber: true,
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        specialization: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Doctor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Doctor",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDoctor(
    @common.Param() params: DoctorWhereUniqueInput,
    @common.Body() data: DoctorUpdateInput
  ): Promise<Doctor | null> {
    try {
      return await this.service.updateDoctor({
        where: params,
        data: data,
        select: {
          address: true,
          contactNumber: true,
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          specialization: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Doctor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Doctor",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDoctor(
    @common.Param() params: DoctorWhereUniqueInput
  ): Promise<Doctor | null> {
    try {
      return await this.service.deleteDoctor({
        where: params,
        select: {
          address: true,
          contactNumber: true,
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          specialization: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/diagnoses")
  @ApiNestedQuery(DiagnosisFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Diagnosis",
    action: "read",
    possession: "any",
  })
  async findDiagnoses(
    @common.Req() request: Request,
    @common.Param() params: DoctorWhereUniqueInput
  ): Promise<Diagnosis[]> {
    const query = plainToClass(DiagnosisFindManyArgs, request.query);
    const results = await this.service.findDiagnoses(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        description: true,

        doctor: {
          select: {
            id: true,
          },
        },

        id: true,

        patient: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/diagnoses")
  @nestAccessControl.UseRoles({
    resource: "Doctor",
    action: "update",
    possession: "any",
  })
  async connectDiagnoses(
    @common.Param() params: DoctorWhereUniqueInput,
    @common.Body() body: DiagnosisWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      diagnoses: {
        connect: body,
      },
    };
    await this.service.updateDoctor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/diagnoses")
  @nestAccessControl.UseRoles({
    resource: "Doctor",
    action: "update",
    possession: "any",
  })
  async updateDiagnoses(
    @common.Param() params: DoctorWhereUniqueInput,
    @common.Body() body: DiagnosisWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      diagnoses: {
        set: body,
      },
    };
    await this.service.updateDoctor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/diagnoses")
  @nestAccessControl.UseRoles({
    resource: "Doctor",
    action: "update",
    possession: "any",
  })
  async disconnectDiagnoses(
    @common.Param() params: DoctorWhereUniqueInput,
    @common.Body() body: DiagnosisWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      diagnoses: {
        disconnect: body,
      },
    };
    await this.service.updateDoctor({
      where: params,
      data,
      select: { id: true },
    });
  }
}
