/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PrescriptionService } from "../prescription.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PrescriptionCreateInput } from "./PrescriptionCreateInput";
import { Prescription } from "./Prescription";
import { PrescriptionFindManyArgs } from "./PrescriptionFindManyArgs";
import { PrescriptionWhereUniqueInput } from "./PrescriptionWhereUniqueInput";
import { PrescriptionUpdateInput } from "./PrescriptionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PrescriptionControllerBase {
  constructor(
    protected readonly service: PrescriptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Prescription })
  @nestAccessControl.UseRoles({
    resource: "Prescription",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPrescription(
    @common.Body() data: PrescriptionCreateInput
  ): Promise<Prescription> {
    return await this.service.createPrescription({
      data: {
        ...data,

        diagnosis: data.diagnosis
          ? {
              connect: data.diagnosis,
            }
          : undefined,

        medication: data.medication
          ? {
              connect: data.medication,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        diagnosis: {
          select: {
            id: true,
          },
        },

        dosage: true,
        frequency: true,
        id: true,

        medication: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Prescription] })
  @ApiNestedQuery(PrescriptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Prescription",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prescriptions(@common.Req() request: Request): Promise<Prescription[]> {
    const args = plainToClass(PrescriptionFindManyArgs, request.query);
    return this.service.prescriptions({
      ...args,
      select: {
        createdAt: true,

        diagnosis: {
          select: {
            id: true,
          },
        },

        dosage: true,
        frequency: true,
        id: true,

        medication: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Prescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prescription",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prescription(
    @common.Param() params: PrescriptionWhereUniqueInput
  ): Promise<Prescription | null> {
    const result = await this.service.prescription({
      where: params,
      select: {
        createdAt: true,

        diagnosis: {
          select: {
            id: true,
          },
        },

        dosage: true,
        frequency: true,
        id: true,

        medication: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Prescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prescription",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePrescription(
    @common.Param() params: PrescriptionWhereUniqueInput,
    @common.Body() data: PrescriptionUpdateInput
  ): Promise<Prescription | null> {
    try {
      return await this.service.updatePrescription({
        where: params,
        data: {
          ...data,

          diagnosis: data.diagnosis
            ? {
                connect: data.diagnosis,
              }
            : undefined,

          medication: data.medication
            ? {
                connect: data.medication,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          diagnosis: {
            select: {
              id: true,
            },
          },

          dosage: true,
          frequency: true,
          id: true,

          medication: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Prescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prescription",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePrescription(
    @common.Param() params: PrescriptionWhereUniqueInput
  ): Promise<Prescription | null> {
    try {
      return await this.service.deletePrescription({
        where: params,
        select: {
          createdAt: true,

          diagnosis: {
            select: {
              id: true,
            },
          },

          dosage: true,
          frequency: true,
          id: true,

          medication: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
